version: '3'

services:

  db:
    image: mysql:5.7
    volumes:
     - db_data:/var/lib/mysql
     - ./db/dumps:/dumps
    environment:
     MYSQL_ROOT_PASSWORD: A123456
     MYSQL_DATABASE: om30_dev
     MYSQL_USER: om30
     MYSQL_PASSWORD: A123456

  web:
    build: 
      context: .
      dockerfile: ./dev.Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    working_dir: /usr/src/app
    restart: always
    ports:
      - "82:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
      - redis
    # Keep the stdin open, so we can attach to our app container's process and do things such as
    # byebug  , etc:
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    env_file:
      - .env.docker

#  sidekiq:
#    build:
#      context: .
#      dockerfile: ./dev.Dockerfile
#    entrypoint: /usr/src/app/development-entrypoint
#    #command: bundle exec sidekiq -C config/sidekiq.yml
#    command: sidekiq -c 25 -q default -C config/sidekiq.yml
#    working_dir: /usr/src/app
#    restart: always
#    volumes:
#      - ./:/usr/src/app
#    links:
#      - db
#      - redis
#    # Keep the stdin open, so we can attach to our app container's process and do things such as
#    # byebug, etc:
#    stdin_open: true
#    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
#    tty: true
#    env_file:
#      - .env.docker

  redis:
    image: redis

volumes:
   db_data:
